### ISSUE TITLE
在線上環境，因為無法「新增照片」，所以問卷流程卡住。但「新增照片」應該是非必填

### ISSUE THREAD

**Issue by Neilxx** [OH-SHOWN/ohshown-frontend#66]
**Describe the bug**
在 local 環境，問卷就算不上傳照片，也可以按下一步進到下一頁
但是在[線上環境](http://ohshown.site:8080/)，不上傳照片就沒辦法下一步，而且目前因為這個 [issue](https://github.com/tai271828/disfactory-backend/issues/38)，線上環境無法上傳照片，所以問卷流程會卡住

**To Reproduce**
1. 去 [線上環境](http://ohshown.site:8080/)
2. 點「我相通報疑似黑熊出沒」按鈕，再點「選擇此地點」，到問卷的下一頁
3. 按下一步，會沒有反應

**Expected behavior**
在上面的 3. 按下一步，會進到問卷的下一頁

**Screenshots**
在 local環境，不用上傳照片，就會顯示 `上傳成功` ，並且可以按下一步進到下一頁
![截圖 2022-03-18 下午1 00 46](https://user-images.githubusercontent.com/22217185/158941103-1fd67986-53ea-4f96-a519-eb8f4055fba6.png)

在線上環境，沒有顯示 `上傳成功` ，按下一步沒反應
![截圖 2022-03-18 下午1 04 47](https://user-images.githubusercontent.com/22217185/158941108-6edf4144-ee0a-44f1-a012-1aff61918da8.png)

**Comment by Neilxx** [comment]
@yanghaochang104 你有空可以幫忙看一下這題嗎 🧐

**Comment by tai271828** [comment]
+100000 I think this "feature" will be very useful until we fix https://github.com/tai271828/disfactory-backend/issues/38

@Neilxx would you mind pinging or assigning someone (there is a button on the top-right) e.g. me next time when you create a new issue? I checked my email inbox and did not see the notification for the creation of this issue. Maybe assigning will help! Thanks!

**Comment by Neilxx** [comment]
@tai271828 sure I will assign you next time!

**Comment by Neilxx** [comment]
Will be closed after #69 merged, deployed and confirmed on development environment.

**Comment by tai271828** [comment]
Deployed. According to this comment https://github.com/OH-SHOWN/ohshown-frontend/pull/69#issuecomment-1096451734 we can close this card.
