### ISSUE TITLE
`datetime` value is not expected from the frontend when parsing in the backend

### ISSUE THREAD

**Issue by tai271828** [OH-SHOWN/ohshown-frontend#71]
**Describe the bug**
When reporting the ohshown event, it seems the 遭遇時間 is incorrect when it is posted to the API of backend. The value of `datetime` seems the same as `created time`.

**To Reproduce**
1. Use the backend source of this pull request https://github.com/OH-SHOWN/ohshown-backend/pull/59
2. Report ohshown event as usual. Make sure you have selected a time value differing from the current time in the "calendar and clock" (see the attached image)
3. Go to the Django admin console of backend. Go to `api/ohshown event`
4. Check the column of "sight see date time". Check the value of your ohshown event entry.

**Expected behavior**
The value of "calendar and clock" we selected is the same as the value of the field "sight see date time" in the django admin console.

**Screenshots**
The "calendar and clock"
![Selection_051](https://user-images.githubusercontent.com/3217432/164989381-815374b8-bfde-4623-bf49-feae8e205c45.png)

The "sight see date time` column:
![Selection_050](https://user-images.githubusercontent.com/3217432/164989411-59e1a769-9e17-4f17-ab1c-7084843e185f.png)

**Additional context**
I am not entirely sure it is a bug of the fontend. This issue may be also my fault from this pull request https://github.com/OH-SHOWN/ohshown-backend/pull/59 . I created this issue because I did not manage to see the root cause in the pull request https://github.com/OH-SHOWN/ohshown-backend/pull/59 . For example, I simply get the `datetime` value from the frontend. See here https://github.com/OH-SHOWN/ohshown-backend/pull/59/files#r857158945 .

**Comment by yanghaochang104** [comment]
My testing showed that the front-end form returned correct sight-see-date-time value in post data field "datetime", that's weird.

By the way, I found the "reported-date" called "date", "reported-time" called "time", "sight-see-date-time" called "datetime" in post data, these are ambiguous and misleading naming, sorry for that.

I'll fix the post data naming in the following days.

**Comment by tai271828** [comment]
https://github.com/OH-SHOWN/ohshown-backend/pull/59 is landed and fixed this issue.
