### ISSUE TITLE
Update wording of 貢獻協議

### ISSUE THREAD

**Issue by tai271828** [OH-SHOWN/ohshown-frontend#78]
**Describe the solution you'd like**
In PR https://github.com/OH-SHOWN/ohshown-frontend/pull/77/files
as is `本網站由 g0v.tw 之 OH!SHOWN 團隊開發`  - sounds OH!SHOWN is belonged to an organization `g0v.tw`
to be `本網站由 g0v.tw 社群中的 OH!SHOWN 團隊所開發` - does it sound  closer to the truth? `g0v.tw` is a community.

**Additional context**
#17

**Comment by joshuay1** [comment]
Fixed the wording of 貢獻協議 and directly committed to main
